version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: ${Swagger_SA_PASSWORD}
        ACCEPT_EULA: "Y"

  swagger-samples:
    image: ${DOCKER_REGISTRY-}swaggersamples
    build:
      context: .
      dockerfile: Swagger-Samples/Dockerfile
